name: Push to Public Repo

on:
  push:
    branches: ["main"]  
  workflow_dispatch:     

jobs:
  deploy-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.CV }}
        with:

          source-directory: 'zad1-cv' 

          destination-github-username: 'Bohdan-Savchuk-77363'

          destination-repository-name: 'link-cv'

          user-email: bsavchu1@stu.vistula.edu.pl
          target-branch: main
